"""add is active to halls

Revision ID: f3123c5cbda1
Revises: 8048ccc22663
Create Date: 2026-09-01 22:55:52.154961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3123c5cbda1'
down_revision: Union[str, Sequence[str], None] = '8048ccc22663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'function_halls',
    sa.Column(
        'is_active',
        sa.Boolean(),
        nullable=False,
        server_default=sa.true()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_halls', 'is_active')
    # ### end Alembic commands ###
